default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: <%= Figaro.env.database_name %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  url: <%= Figaro.env.DATABASE_URL %>

production:
  # <<: *default
  # database: <%= Figaro.env.database_name %>
  # username: <%= Figaro.env.database_username %>
  # password: <%= Figaro.env.database_password %>
  adapter: postgresql
  encoding: unicode
  database: <%= Figaro.env.database_name %>
  pool: 5
  host: <%= Figaro.env.database_host %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
