default: &default
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  adapter: <%= Figaro.env.adapter %>
  encoding: <%= Figaro.env.encoding %>
  database: <%= Figaro.env.database_name %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  url: <%= Figaro.env.DATABASE_URL %>

production:
  adapter: <%= Figaro.env.adapter %>
  encoding: <%= Figaro.env.encoding %>
  database: <%= Figaro.env.database_name %>
  host: <%= Figaro.env.database_host %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
